version: 2

jobs:
  build:
    branches:
      only:
      - develop
      - master
      - /ci-.*/
    resource_class: large
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        command: |
          DATE=`date +%s`
          echo ${DATE}
          MY_VARIABLE="Foo"
          echo 'export MY_ENV=${MY_VARIABLE}' >> $BASH_ENV
    - run:
        command: echo ${MY_ENV}
    - run:
        name: Run Staging
        command: ./gradlew assembleDebug
    - store_artifacts:
        path: app/build/outputs/apk/debug
        destination: apk
    - run:
        name: Run Test APK
        command: ./gradlew assembleAndroidTest
    - store_artifacts:
        path: app/build/outputs/apk/androidTest/debug
        destination: apk
    - run:
        name: Decode firebase client-secret.json
        command: echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/client-secret.json
    - run:
        name: Auth firebase service account
        command: sudo gcloud beta auth activate-service-account firebase-adminsdk-ii296@testlab-4372f.iam.gserviceaccount.com --key-file ${HOME}/client-secret.json
    - run:
        name: Set firebase account
        command: sudo gcloud beta config set account firebase-adminsdk-ii296@testlab-4372f.iam.gserviceaccount.com
    - run:
        name: Set firebase project
        command: sudo gcloud beta config set project testlab-4372f
    - run:
        name: Starting robo test
        command: sudo gcloud beta firebase test android run --app app/build/outputs/apk/debug/app-debug.apk --type robo --device model=Nexus6,version=25 --timeout 1m --async
    - run:
        name: Run Signing Report
        command: ./gradlew signingReport