version: 2

jobs:
  build:
    branches:
      only:
      - develop
      - master
      - /ci-.*/
    resource_class: large
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        run:
        command: |
          echo 'export MY_ENV=`date +%s`' >> $BASH_ENV
    - run:
        command: echo ${MY_ENV}
    - run:
        name: Run Staging
        command: ./gradlew assembleDebug
    - store_artifacts:
        path: app/build/outputs/apk/debug
        destination: apk
    - run:
        name: Run Test APK
        command: ./gradlew assembleAndroidTest
    - store_artifacts:
        path: app/build/outputs/apk/androidTest/debug
        destination: apk
    - run:
        name: Decode firebase client-secret.json
        command: echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/client-secret.json
    - run:
        name: Auth firebase service account
        command: sudo gcloud beta auth activate-service-account firebase-adminsdk-ii296@testlab-4372f.iam.gserviceaccount.com --key-file ${HOME}/client-secret.json
    - run:
        name: Set firebase account
        command: sudo gcloud beta config set account firebase-adminsdk-ii296@testlab-4372f.iam.gserviceaccount.com
    - run:
        name: Set firebase project
        command: sudo gcloud beta config set project testlab-4372f
    - run:
        name: Starting robo test
        command: |
          if [ $TL_TEST_DATE == null || $TL_TEST_DATE != `date +%d` ];
            then
              echo 'export TL_TEST_COUNT=0' >> $BASH_ENV
            fi

          if [ $TL_TEST_COUNT != null && $TL_TEST_COUNT >= 10 ];
            then
              echo "TestLab test count reached the limit"
            else
              if [ $PREVIOUS_TEST_HOUR != null && $PREVIOUS_TEST_HOUR == `date +%H` ];
                then
                  echo "TestLab robo won't run because the previous test happened no long ago"
                else
                  echo 'export PREVIOUS_TEST_HOUR=`date +%H`' >> $BASH_ENV
                  echo 'export TL_TEST_COUNT=$(($TL_TEST_COUNT+1))' >> $BASH_ENV
                  echo 'export TL_TEST_DATE=`date +%d`' >> $BASH_ENV
                  echo $PREVIOUS_TEST_HOUR
                  echo $TL_TEST_COUNT
                  echo $TL_TEST_DATE
                  sudo gcloud beta firebase test android run --app app/build/outputs/apk/debug/app-debug.apk --type robo --device model=Nexus6,version=25 --timeout 1m --async
                fi
            fi
    - run:
        name: Run Signing Report
        command: ./gradlew signingReport